# Generated by Django 5.2.8 on 2025-11-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatreino',
            name='motivo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fichatreino',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
