# Generated by Django 5.2.8 on 2025-11-25 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0002_fichatreino_motivo_fichatreino_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treinodiario',
            name='ficha',
        ),
        migrations.AddField(
            model_name='fichatreino',
            name='ativa',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='treinos.fichatreino')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='treinodiario',
            name='treino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='treinos.treino'),
        ),
        migrations.CreateModel(
            name='TreinoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveIntegerField()),
                ('repeticoes', models.PositiveIntegerField()),
                ('ordem', models.PositiveIntegerField()),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinos.exercicio')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='treinos.treino')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('treino', 'ordem')},
            },
        ),
        migrations.AddField(
            model_name='treinoprogresso',
            name='treino_diario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progresso', to='treinos.treinodiario'),
        ),
        migrations.AlterUniqueTogether(
            name='treinoprogresso',
            unique_together={('treino_diario', 'exercicio')},
        ),
        migrations.RemoveField(
            model_name='treinoprogresso',
            name='treino',
        ),
        migrations.DeleteModel(
            name='FichaExercicio',
        ),
    ]
