# Generated by Django 5.2.8 on 2025-11-25 21:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0003_remove_treinodiario_ficha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_aluno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treinodiario',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treinodiario',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='treinodiario',
            name='tempo_medio_exercicio',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treinodiario',
            name='tempo_total',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
